# Generated by Django 4.2.20 on 2025-03-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('moeda', models.CharField(max_length=10)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'unique_together': {('data', 'moeda')},
            },
        ),
    ]
